export const horse = {
	namespaced: true,
	state: {
		horses: [
			{
				id: 1,
				name: 'Tucker',
				travelledDistance: 120,
				speed: 0,
				finish: false,
				score: 0,
				scoreTime: 0,
				color: '#3b302f',
				run: false,
			},
			{
				id: 2,
				name: 'Dakota',
				travelledDistance: 60,
				speed: 0,
				finish: false,
				score: 0,
				scoreTime: 0,
				color: '#a97452',
				run: false,
			},

			{
				id: 3,
				name: 'Cash',
				travelledDistance: 90,
				speed: 0,
				finish: false,
				score: 0,
				scoreTime: 0,
				color: '#613f24',
				run: false,
			},
			{
				id: 4,
				name: 'Cisco',
				travelledDistance: 160,
				speed: 0,
				finish: false,
				score: 0,
				scoreTime: 0,
				color: '#c9b89f',
				run: false,
			},
			{
				id: 5,
				name: 'Whiskey',
				travelledDistance: 270,
				speed: 0,
				finish: false,
				score: 0,
				scoreTime: 0,
				color: '#b6b6b6',
				run: false,
			},
			{
				id: 6,
				name: 'Blue',
				travelledDistance: 172,
				speed: 0,
				finish: false,
				score: 0,
				scoreTime: 0,
				color: '#d09761',
				run: false,
			},
			{
				id: 7,
				name: 'Molly',
				travelledDistance: 60,
				speed: 0,
				finish: false,
				score: 0,
				scoreTime: 0,
				color: '#cc784c',
				run: false,
			},
			{
				id: 8,
				name: 'Ranger',
				travelledDistance: 55,
				speed: 0,
				finish: false,
				score: 0,
				scoreTime: 0,
				color: '#826256',
				run: false,
			}
		]

	}
}